---
title: "modeling pilot results"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)

inferenceData_tidy <- read.csv('poster_data/inference_data.csv')
learningData_tidy <- read.csv('poster_data/learning_data.csv')
modelData <- read.csv('poster_data/0.52coh_10_thresh_confidence.csv')
nSubs <- 9

modelData <- modelData %>%
  filter(is.na(noise1Frames)==F) %>%
  mutate(cue = factor(cue),
         threshold = factor(threshold),
         congruent = case_when(cue==0.8 & congruent==1 ~ 'congruent',
                               cue==0.8 & congruent==0 ~ 'incongruent',
                               cue==0.5 & congruent==1 ~ 'neutral',
                               cue==0.5 & congruent==0 ~ 'neutral'),
         congruent = factor(congruent, levels=c('incongruent', 'neutral', 'congruent')),
         accuracyFactor = factor(forcedChoice, levels=c(1,0), labels=c('correct', 'incorrect')),
         inverseConf = 1/accumulatorDifference,
         logInverseConf = log(inverseConf),
         respPeriod = case_when(RT <= noise1Frames ~ 1,
                                RT <= noise1Frames + signal1Frames ~ 2,
                                RT <= noise1Frames + signal1Frames + noise2Frames ~ 3,
                                RT > noise1Frames + signal1Frames + noise2Frames ~ 4))

rt_quartile <- quantile(modelData$RT, names=F)
noise_quartile <- quantile(modelData$noise1Frames, names=F)
modelData <- modelData %>%
  mutate(rt_quartile = case_when(RT >= rt_quartile[1] & RT < rt_quartile[2] ~ 1,
                   RT >= rt_quartile[2] & RT < rt_quartile[3] ~ 2,
                   RT >= rt_quartile[3] & RT < rt_quartile[4] ~ 3,
                   RT >= rt_quartile[4] ~ 4),
         noise1quartile = case_when(noise1Frames >= noise_quartile[1] & noise1Frames < noise_quartile[2] ~ 1,
                                    noise1Frames >= noise_quartile[2] & noise1Frames < noise_quartile[3] ~ 2,
                                    noise1Frames >= noise_quartile[3] & noise1Frames < noise_quartile[4] ~ 3,
                                    noise1Frames >= noise_quartile[4] ~ 4),
         RT = scale(log(RT)))

inferenceData_tidy <- inferenceData_tidy %>% 
  filter(pilotGroup == 'group2') %>%
  mutate(accuracyFactor=factor(accuracy, levels=c(1,0), labels=c('correct', 'incorrect')),
         congruent = factor(congruent, levels=c('incongruent', 'neutral', 'congruent')))
```


## accuracy: simulated / predicted
```{r, include=FALSE}
individualSummary_model <- modelData %>%
  group_by(subID, congruent) %>%
  summarise(propCorrect_raw = mean(rawChoice, na.rm=T),
            propCorrect_forced = mean(forcedChoice),
            meanRT = mean(RT))

groupSummary_model <- modelData %>%
  group_by(congruent) %>%
  summarise(propCorrect_raw = mean(rawChoice, na.rm=T),
            propCorrect_forced = mean(forcedChoice),
            meanRT = mean(RT),
            raw_sem = sd(rawChoice, na.rm=T)/sqrt(9),
            forced_sem = sd(forcedChoice)/sqrt(9),
            RT_sem = sd(RT)/sqrt(9))

sim <- ggplot(groupSummary_model, aes(x=congruent, y=propCorrect_forced, color=congruent, fill=congruent)) +
  geom_hline(yintercept = 0.5, linewidth=0.15) +
  geom_col(position = position_dodge(width=0.9), width=0.75, fill='white', linewidth=2) +
  geom_errorbar(aes(ymin=propCorrect_forced - forced_sem, ymax=propCorrect_forced + forced_sem), width=0.1,
                position = position_dodge(width=0.9), color='gray25') +
  geom_point(size=2, color='gray25', position = position_dodge(width=0.25)) +
  geom_point(data=individualSummary_model, position=position_jitterdodge(dodge.width=0.25, jitter.width = 0.15), 
             color='gray25', shape=21, size=2, alpha=0.7) +
  labs(y = 'proportion correct', x='', title='simulated') + 
  theme_classic() +
  theme(legend.position = 'none',
        text = element_text(size=14))
```

## accuracy: measured / observed
```{r accuracy summary, echo=FALSE, message=FALSE, warning=FALSE, out.width='60%'}

# compute accuracy within individuals
individualSummary <- inferenceData_tidy %>%
  group_by(subID, congruent) %>%
  summarise(propCorrect = mean(accuracy),
            meanRT = mean(zlogRT),
            meanZConf = mean(zConf))

# compute accuracy across individuals
groupSummary <- inferenceData_tidy %>%
  group_by(congruent) %>%
  summarise(propCorrect = mean(accuracy),
            accuracy_sem = sd(accuracy) / sqrt(nSubs),
            meanRT = mean(zlogRT),
            RT_sem = sd(zlogRT) / sqrt(nSubs),
            meanConf = mean(zConf),
            conf_sem = sd(zConf)/sqrt(nSubs)) 

# plot accuracy
obs <- ggplot(groupSummary, aes(x=congruent, y=propCorrect, fill=congruent)) +
  ylim(0,1) +
  theme_classic() + 
  geom_hline(yintercept=0.5, linewidth=0.15) +
  geom_col(position = position_dodge(width=0.25), width = 0.9) +
  geom_errorbar(aes(ymin=propCorrect - accuracy_sem, ymax = propCorrect + accuracy_sem), width=0.1,
                position = position_dodge(width=0.25), color='gray25') +
  geom_point(size=2, color='gray25',position = position_dodge(width=0.25)) +
  geom_point(data=individualSummary, position=position_jitterdodge(dodge.width=0.25, jitter.width = 0.15), 
             color='gray25', shape=21, size=2, alpha=0.7) +
  labs(x='', y='proportion correct', title='observed') +
  theme(text = element_text(size=14),
        legend.position = 'none')
```

```{r, include=FALSE, fig.width='70%'}
sim + obs
```


## RT plot: simulated / predicted
```{r}
individualSummary_model <- modelData %>%
  group_by(subID, congruent, accuracyFactor) %>%
  summarise(meanRT = mean(RT))

groupSummary_model <- modelData %>%
  group_by(congruent, accuracyFactor) %>%
  summarise(meanRT = mean(RT),
            RT_sem = sd(RT)/sqrt(9))

sim <- ggplot(groupSummary_model, aes(x=congruent, y=meanRT, color=congruent, fill=congruent)) +
  facet_wrap(~ accuracyFactor) + 
  geom_hline(yintercept=0, linewidth=0.15) +
  geom_col(position = position_dodge(width=0.9), width=0.9, fill='white', linewidth=2) +
  geom_errorbar(aes(ymin=meanRT - RT_sem, ymax=meanRT + RT_sem), width=0.1,
                position = position_dodge(width=0.9), color='gray25') +
  geom_point(size=2, color='gray25', position = position_dodge(width=0.25)) +
  geom_point(data=individualSummary_model, position=position_jitterdodge(dodge.width=0.25, jitter.width = 0.15), 
             color='gray25', shape=21, size=2, alpha=0.7) +
  labs(x='', y='RT (simulated)') +
  theme_classic() +
  theme(legend.position='none',
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(size=10))
```

## RT plot: measured / observed
```{r RT, warning=FALSE, echo=FALSE, message=FALSE, out.width='60%'}
groupSummary <- inferenceData_tidy %>%
  group_by(accuracyFactor, congruent) %>%
  summarise(meanRT = mean(zlogRT),
         RT_sem = sd(zlogRT) / sqrt(nSubs),
         meanConf = mean(zConf),
         conf_sem = sd(zConf) / sqrt(nSubs))

# then compute individual summaries
individualSummary <- inferenceData_tidy %>%
  group_by(accuracyFactor, congruent, subID) %>%
  summarise(meanRT = mean(zlogRT),
            meanConf = mean(zConf))

# plot accuracy * RT interaction
obs <- groupSummary %>%
ggplot(aes(x=congruent, y=meanRT, fill=congruent)) +
  theme_classic() + 
  facet_wrap(~accuracyFactor) +
  geom_hline(yintercept=0, linewidth=0.15) +
  geom_col(color='gray25') + 
  geom_errorbar(aes(ymin=meanRT - RT_sem, ymax = meanRT + RT_sem), width=0.1,
                color='gray25') +
  geom_point(size=2, color='gray25',position = position_dodge(width=0.25)) +
  geom_point(data=individualSummary, position=position_jitterdodge(dodge.width=0.25, jitter.width = 0.25), 
             color='gray25', shape=21, size=2, alpha=0.9) +
  labs(x='', y = 'Mean RT') + 
  theme(text = element_text(size=14),
        legend.position = 'none')
```

```{r, include=FALSE}
sim + obs
```


## RT by first noise period
```{r}
groupSummary_model <- modelData %>%
  group_by(noise1quartile, congruent) %>%
  summarise(meanRT = mean(RT),
            RT_sem = sd(RT)/sqrt(nSubs))

individualSummary_model <- modelData %>%
  group_by(noise1quartile, congruent, subID) %>%
  summarise(meanRT = mean(RT))

sim <- groupSummary_model %>%
  ggplot(aes(x=noise1quartile, y=meanRT, color=congruent, fill=congruent, group=congruent)) +
  geom_hline(yintercept=0, linewidth=0.15) +
  geom_pointrange(aes(ymin=meanRT - RT_sem, ymax = meanRT + RT_sem)) +
  geom_line() +
  theme_classic() +
  labs(x = 'first noise duration', y='mean RT', title='simulated')
```

```{r noise summaries, message=FALSE, echo=FALSE, out.width="70%"}
fnSummary_group <- inferenceData_tidy %>%
  group_by(firstNoise_quartile, congruent) %>%
  summarise(propCorrect = mean(accuracy),
            accuracy_sem = sd(accuracy)/sqrt(nSubs),
            meanConf = mean(zConf),
            conf_sem = sd(zConf)/sqrt(nSubs),
            meanRT = mean(zlogRT),
            RT_sem = sd(zlogRT)/sqrt(nSubs))

fnSummary_individual <- inferenceData_tidy %>%
  group_by(firstNoise_quartile, congruent, subID) %>%
  summarise(propCorrect = mean(accuracy),
            meanConf = mean(zConf),
            meanRT = mean(zlogRT))

# RT as a function of trial noise
obs <- fnSummary_group %>%
  ggplot(aes(x=firstNoise_quartile, y=meanRT, color=congruent, fill=congruent, group=congruent)) +
  geom_hline(yintercept=0, linewidth=0.15) +
  geom_pointrange(aes(ymin=meanRT - RT_sem, ymax = meanRT + RT_sem)) +
  geom_line() +
  theme_classic() +
  labs(x = 'first noise duration', y='mean RT', title='observed')
```

```{r}

sim + obs

```


## confidence * RT interaction plot
```{r}
sim <- modelData %>%
  mutate(confidence = scale(inverseConf)) %>%
  group_by(congruent, accuracyFactor) %>%
  summarise(confidence = mean(inverseConf),
            confidence_sem = sd(inverseConf)/sqrt(nSubs),
            RT = mean(RT),
            RT_sem = sd(RT)/sqrt(nSubs)) %>%
  ggplot(aes(x=congruent, y=RT, group=accuracyFactor)) +
  facet_grid(~ accuracyFactor) + 
  geom_pointrange(aes(ymin=RT - RT_sem, ymax = RT + RT_sem, color='black')) +
  geom_line() +
  geom_pointrange(aes(y=confidence, ymin=confidence - confidence_sem, ymax = confidence + confidence_sem, color='gray50')) +
  geom_line(aes(y=confidence), color='gray50', linetype='dashed') +
  labs(y = 'z-score value', x='', title='simulated') +
  theme_classic() +
  scale_color_identity(guide = "legend",
                       name = '',
                       labels = c('RT', 'confidence'))

```

```{r RT conf interaction, warning=FALSE, message=FALSE,echo=FALSE, out.width='60%'}
obs <- groupSummary %>%
  ggplot(aes(x=congruent, y=meanRT, group=accuracyFactor)) +
  facet_grid(~ accuracyFactor) + 
  geom_hline(yintercept=0, linewidth=0.15) + 
  geom_pointrange(aes(ymin=meanRT - RT_sem, ymax = meanRT + RT_sem, color='black')) +
  geom_line() +
  geom_pointrange(aes(y=meanConf, ymin=meanConf - conf_sem, ymax = meanConf + conf_sem, color='gray50')) +
  geom_line(aes(y=meanConf), color='gray50', linetype='dashed') +
  labs(y = 'z-score value', x='', title='observed') +
  theme_classic() +
  scale_color_identity(guide = "legend",
                       name = '',
                       labels = c('RT', 'confidence')) 
```

```{r}
sim + obs + plot_layout(guides = 'collect')
```


## confidence 
```{r}
## confidence as inverse difference
modelData <- modelData %>% mutate(zConf = scale(inverseConf))

modelSummary_group <- modelData %>%
  group_by(accuracyFactor, congruent) %>%
  summarise(confidence = mean(inverseConf),
            logConfidence = mean(logInverseConf),
            sem = sd(inverseConf)/sqrt(nSubs),
            log_sem = sd(logInverseConf) / sqrt(nSubs),
            zconfidence = mean(zConf),
            z_sem = sd(zConf)/sqrt(nSubs))

modelSummary_ind <- modelData %>%
  group_by(accuracyFactor, congruent, subID) %>%
  summarise(confidence = mean(inverseConf),
            logConfidence = mean(logInverseConf),
            zconfidence = mean(zConf))

modelSummary_group %>%
  ggplot(aes(x=congruent, y=confidence, fill=congruent,color=congruent)) +
  theme_classic() + 
  facet_wrap(~accuracyFactor) +
  geom_hline(yintercept=0, linewidth=0.15) +
  geom_col(fill='white',linewidth=2) + 
  geom_errorbar(aes(ymin=confidence - sem, ymax = confidence + sem), width=0.1,
                color='gray25') +
  geom_point(size=2, color='gray25',position = position_dodge(width=0.25)) +
  geom_point(data=modelSummary_ind, position=position_jitterdodge(dodge.width=0.25, jitter.width = 0.25), 
             color='gray25', shape=21, size=2, alpha=0.9) +
  labs(x='', title = '-abs(memoryAccumulator(RT) - visionAccumulator(RT)))') + 
  theme(legend.position = 'none')

sim <- modelSummary_group %>%
  ggplot(aes(x=congruent, y=logConfidence, fill=congruent,color=congruent)) +
  theme_classic() + 
  facet_wrap(~accuracyFactor) +
  geom_hline(yintercept=0, linewidth=0.15) +
  geom_col(fill='white',linewidth=2) + 
  geom_errorbar(aes(ymin=logConfidence - log_sem, ymax = logConfidence + log_sem), width=0.1,
                color='gray25') +
  geom_point(size=2, color='gray25',position = position_dodge(width=0.25)) +
  geom_point(data=modelSummary_ind, position=position_jitterdodge(dodge.width=0.25, jitter.width = 0.25), 
             color='gray25', shape=21, size=2, alpha=0.9) +
  labs(x='', title = 'log(1/abs(memoryAccumulator(RT) - visionAccumulator(RT)))') + 
  theme(legend.position = 'none')
ggsave('logConfidence.png', width=6)
```

```{r confidence, echo=FALSE, warning=FALSE, out.width='60%'}
obs <- groupSummary %>%
  ggplot(aes(x=congruent, y=meanConf, fill=congruent)) +
  theme_classic() + 
  facet_wrap(~accuracyFactor) +
  geom_hline(yintercept=0, linewidth=0.15) +
  geom_col(color='gray25') + 
  geom_errorbar(aes(ymin=meanConf - conf_sem, ymax = meanConf + conf_sem), width=0.1,
                color='gray25') +
  geom_point(size=2, color='gray25',position = position_dodge(width=0.25)) +
  geom_point(data=individualSummary, position=position_jitterdodge(dodge.width=0.25, jitter.width = 0.25), 
             color='gray25', shape=21, size=2, alpha=0.9) +
  labs(x='', y = 'Mean confidence rating (z-scored)', title='measured') + 
  theme(legend.position = 'none')
```

```{r}
sim + obs
```

