---
title: "plot_group_fits"
author: "ari k"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
```

```{r load & tidy data; define helper functions, include=FALSE}
# load cueCorrs
cueCorrs <- read.csv('../tidied_data/all_conditions/estimates.csv') %>%
  group_by(subID) %>%
  mutate(cueCorr = cor(trueCue, subjectiveCue),
         condition = ifelse(subID < 55, 'condition_80cue', 'condition_65cue')) %>%
  filter(is.na(cueCorr)==0) %>%
  select(subID, cueCorr, condition) %>%
  unique()

# load in subjects to exclude
exclude <- scan("belowChanceSubs.txt", what = numeric())

# helper functions
tidy_fits <- function(df) {
  fits_longer <- df %>%
    # Select columns that don't end with "_min" or "_max" to avoid those columns
    select(-ends_with("_min"), -ends_with("_max")) %>%
    # Pivot longer all columns that end with "_fitted"
    pivot_longer(
      cols = ends_with("_fitted"),
      names_to = "parameter",
      values_to = "value"
    ) %>%
    # Remove the "_fitted" suffix from the parameter names
    mutate(parameter = gsub("_fitted$", "", parameter))
  return(fits_longer)
}

outdir <- 'results_summer2025/group_fits/'
```

```{r plot 4 drift}

# load in data
fourDrift_test <- read.csv('../pyDDM/cluster_fitting/testTrial_fits/4drifts_0ndt/results/fits.csv') %>% 
  mutate(model = 'test trials only')
fourDrift <- read.csv('../pyDDM/cluster_fitting/allTrial_fits/4drifts_0ndt/results/fits.csv') %>%
  mutate(model = 'test + catch trials')

fourDrift_all <- rbind(fourDrift_test, fourDrift) %>% 
  unique() %>% tidy_fits() %>%
  rename(cueLevel = condition,
         subset = model) %>%
  mutate(cueLevel = ifelse(cueLevel=='condition_80cue', '0.8', '0.65'),
         parameter = ifelse(parameter=='noise2', paste0(parameter, '_cue'), parameter))
  

plot_noise2 <- function(data, title) {
  p <- ggplot(data, aes(x=parameter, y=value, color=subset, fill=subset)) +
  theme_bw() + facet_wrap(~ cueLevel) +
  stat_summary(aes(fill=subset), fun.y = 'mean', geom='col', position=position_dodge(width=0.9)) +
  #stat_summary(aes(group=subset), fun = 'mean', geom='line', position=position_dodge(width=0.9)) +
  stat_summary(aes(group=subset), fun.data = 'mean_se', geom='pointrange', position=position_dodge(width=0.9), color='black') +
  scale_color_manual(values = c('gray70', 'gray40')) + scale_fill_manual(values = c('gray70', 'gray40')) +
  labs(y = 'fitted noise2 drift', title = title) +
  scale_y_continuous(breaks = c(seq(0, 1.25, 0.1)))
  
  return(p)
}

p1 <- fourDrift_all %>% 
  filter(parameter %in% c('noise2_cue', 'noise2_50')) %>%
  mutate(cueLevel = factor(cueLevel, levels=c('0.65', '0.8'), labels=c('cueLevel: 0.65', 'cueLevel: 0.8'))) %>% 
  plot_noise2(., 'fourDrift: all subjects') 
  
p2 <- fourDrift_all %>%
  filter(parameter %in% c('noise2_cue', 'noise2_50'),
         !subID %in% exclude) %>%
  mutate(cueLevel = factor(cueLevel, levels=c('0.65', '0.8'), labels=c('cueLevel: 0.65', 'cueLevel: 0.8'))) %>% 
  plot_noise2(., 'fourDrift: above-chance subjects only')

(p1 + p2) + plot_layout(guides = 'collect')

p3 <- fourDrift_test %>%
  filter(!subID %in% exclude) %>% 
  select(c(subID, condition, noise2_fitted, noise2_50_fitted)) %>%
  tidy_fits() %>%
  mutate(trueCue = factor(case_when(parameter=='noise2' & condition=='condition_80cue' ~ 0.8,
                             parameter=='noise2' & condition=='condition_65cue' ~ 0.65,
                             parameter=='noise2_50' ~ 0.5))) %>%
  ggplot(aes(x=trueCue, y=value)) + theme_bw() +
  facet_wrap(~condition) +
  stat_summary(fun.y = 'mean', geom='col', position=position_dodge(width=0.9)) +
  stat_summary(fun.data = 'mean_se', geom='pointrange', position=position_dodge(width=0.9), color='black') +
  labs(y = 'fitted noise2 drift',
       title = 'above-chance subs & test trials only: group trends')

p4 <- fourDrift_test %>%
  filter(!subID %in% exclude) %>% 
  select(c(subID, condition, noise2_fitted, noise2_50_fitted)) %>%
  tidy_fits() %>%
  mutate(trueCue = factor(case_when(parameter=='noise2' & condition=='condition_80cue' ~ 0.8,
                             parameter=='noise2' & condition=='condition_65cue' ~ 0.65,
                             parameter=='noise2_50' ~ 0.5))) %>%
  ggplot(aes(x=trueCue, y=value)) + theme_bw() +
  facet_wrap(~condition) +
  #stat_summary(fun.y = 'mean', geom='col', position=position_dodge(width=0.9)) +
  #stat_summary(fun.data = 'mean_se', geom='pointrange', position=position_dodge(width=0.9), color='black') +
  geom_line(aes(group=subID), alpha=0.5) +
  geom_point(aes(group=subID), alpha=0.5) +
  labs(y = 'fitted noise2 drift',
       title = 'individual trends')

(p1 + p2) / (p3 + p4) + plot_layout(guides = 'collect')
ggsave(paste0(outdir, '4drift_fitComparison.png'), width=12, height=7, dpi='retina')
```

```{r plot congIncong}

# load in data
congIncong_test <- read.csv('../pyDDM/cluster_fitting/testTrial_fits/4drifts_0ndt_congIncong/results/fits.csv') %>% 
  mutate(model = 'test trials only')
congIncong <- read.csv('../pyDDM/cluster_fitting/allTrial_fits/4drifts_0ndt_congIncong/results/fits.csv') %>%
  mutate(model = 'test + catch trials')

congIncong_all <- rbind(congIncong_test, congIncong) %>% 
  unique() %>% tidy_fits() %>% rename(subset = model) %>%
  filter(parameter %in% c('noise2_cong', 'noise2_incong', 'noise2_neut')) %>%
  mutate(parameter=factor(parameter, levels = c('noise2_incong', 'noise2_neut', 'noise2_cong')))
  

plot_noise2 <- function(data, title) {
  p <- ggplot(data, aes(x=parameter, y=value, fill=condition)) +
  theme_bw() + facet_wrap(~ subset) +
  stat_summary(fun.y = 'mean', geom='col', position=position_dodge(width=0.9)) +
  stat_summary(fun.data = 'mean_se', geom='pointrange', position=position_dodge(width=0.9), color='black') +
  scale_color_manual(values = c('gray70', 'gray40')) + scale_fill_manual(values = c('gray70', 'gray40')) +
  labs(y = 'fitted noise2 drift', title = title)
  
  return(p)
}

p1 <- congIncong_all %>% 
  filter(parameter %in% c('noise2_cong', 'noise2_incong', 'noise2_neut')) %>%
  #mutate(cueLevel = factor(cueLevel, levels=c('0.65', '0.8'), labels=c('cueLevel: 0.65', 'cueLevel: 0.8'))) %>% 
  plot_noise2(., 'congIncong: all subjects') 
  
p2 <- congIncong_all %>%
  filter(parameter %in% c('noise2_cong', 'noise2_incong', 'noise2_neut'),
         !subID %in% exclude) %>%
  #mutate(cueLevel = factor(cueLevel, levels=c('0.65', '0.8'), labels=c('cueLevel: 0.65', 'cueLevel: 0.8'))) %>% 
  plot_noise2(., 'congIncong: above-chance subjects only')

(p1 + p2) + plot_layout(guides = 'collect')

p3 <- congIncong_test %>%
  filter(!subID %in% exclude) %>% 
  select(c(subID, condition, noise2_cong_fitted, noise2_incong_fitted, noise2_neut_fitted)) %>%
  tidy_fits() %>%
  mutate(parameter = factor(parameter, levels=c('noise2_incong', 'noise2_neut', 'noise2_cong'))) %>%
  ggplot(aes(x=parameter, y=value, fill=condition)) + theme_bw() +
  facet_wrap(~condition) +
  stat_summary(fun.y = 'mean', geom='col', position=position_dodge(width=0.9)) +
  stat_summary(fun.data = 'mean_se', geom='pointrange', position=position_dodge(width=0.9), color='black') +
  scale_fill_manual(values = c('gray70', 'gray40')) +
  labs(y = 'fitted noise2 drift',
       title = 'above-chance subs & test trials only: group trends')

p4 <- congIncong_test %>%
  filter(!subID %in% exclude) %>% 
  select(c(subID, condition, noise2_cong_fitted, noise2_incong_fitted, noise2_neut_fitted)) %>%
  tidy_fits() %>%
  mutate(parameter = factor(parameter, levels=c('noise2_incong', 'noise2_neut', 'noise2_cong'))) %>%
  ggplot(aes(x=parameter, y=value)) + theme_bw() +
  facet_wrap(~condition) +
  #stat_summary(fun.y = 'mean', geom='col', position=position_dodge(width=0.9)) +
  #stat_summary(fun.data = 'mean_se', geom='pointrange', position=position_dodge(width=0.9), color='black') +
  geom_line(aes(group=subID), alpha=0.5) +
  geom_point(aes(group=subID), alpha=0.5) +
  labs(y = 'fitted noise2 drift',
       title = 'individual trends')

(p1 + p2) / (p3 + p4) + plot_layout(guides = 'collect')
ggsave(paste0(outdir, 'congIncong_fitComparison.png'), width=15, height=7, dpi='retina')

```