---
title: "pilot analyses: subjective cue probabilities"
output: 
  github_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

# SETUP
```{r load packages, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(tidyverse)
library(patchwork)
library(lme4)
library(lmerTest)
library(emmeans)
library(knitr)
library(pals)

# potentially useful in the future
library(performance) # for easy model comparisons
# library(jtools) # for alternative model summaries
library(sjPlot) # for formatting model result tables
# library(MetBrewer) # for pretty art-inspired color palettes
```

```{r load data, include=FALSE}

# load learning data (first round)
learning_files = list.files('../data', full.names = TRUE, pattern='learning.csv', recursive = T)
learning_keep_idx <- grep('excluded', learning_files, invert=T)
learning_df = do.call(rbind, lapply(learning_files[learning_keep_idx], function(x) { read.csv(x, header = TRUE)} )) 
# load second round of learning data (if applicable)
learning2_files = list.files('../data', full.names = TRUE, pattern='learning2.csv', recursive = T)
learning2_keep_idx <- grep('excluded', learning2_files, invert=T)
learning2_df = do.call(rbind, lapply(learning2_files[learning2_keep_idx], function(x) { read.csv(x, header = TRUE)} )) # append round 2 onto round 1 dataframe
learning_df <- rbind(learning_df, learning2_df)

# load learning validation data
learnVal_files = list.files('../data', full.names = TRUE, pattern='learningValidation.csv', recursive = T)
learnVal_keep_idx <- grep('excluded', learnVal_files, invert=T)
learnVal_df = do.call(rbind, lapply(learnVal_files[learnVal_keep_idx], function(x) { read.csv(x, header = TRUE)} )) 

# load inference data
inference_files = list.files('../data', full.names = TRUE, pattern='cuedInference_table.csv', recursive = T)
inference_keep_idx <- grep('excluded', inference_files, invert=T)
inference_df = do.call(rbind, lapply(inference_files[inference_keep_idx], function(x) { read.csv(x, header = TRUE)} )) 

rm(calibration_files, calibration_keep_idx, cohVal_files, inference_files, inference_keep_idx, learning_files, learning_keep_idx, learning2_files, learning2_keep_idx, learnVal_files, learnVal_keep_idx)
```

```{r tidy data, include=FALSE}

### tidy learning
learning_df <- learning_df %>%
  mutate(subID = factor(subID),
         imageIdx = factor(imageIdx),
         cueIdx = factor(cueIdx),
         congruent = factor(congruent, levels=c("0", "1", "NaN"), labels=c('incongruent', 'congruent', 'neutral')),
         imgLockedRT = RT - cueDuration) %>%
  arrange(subID) %>%
  mutate(trial = case_when(subID=='32' ~ row_number(),
                           subID!='32' ~ trial))

### tidy learning validation
learnVal_df <- learnVal_df %>%
  mutate(subID = factor(subID),
         cueIdx = factor(cueIdx),
         trueCue = case_when(cueIdx != '3' ~ 80,
                             cueIdx == '3' ~ 50),
         estimate = case_when(cueIdx == '3' & estimate < 50 ~ 100-estimate, 
                              cueIdx == '3' & estimate >= 50 ~ estimate,
                              cueIdx != '3' ~ estimate)) %>%
  rename(cueName = cueString)

### tidy inference
inference_df <- inference_df %>%
  mutate(subID = factor(subID),
         targetIdx = factor(targetIdx),
         congruent = factor(congruent, levels=c("0", "1", "NaN"), labels=c('incongruent', 'congruent', 'neutral')),
         cueCongResponse_obj = case_when(cueIdx < 3 & response==cueIdx ~ 1,
                                         cueIdx < 3 & response!=cueIdx ~ 0,
                                         cueIdx==3 ~ NA),
         accuracyFactor = factor(case_when(accuracy==1 ~ 1,
                                    accuracy==0 ~ 0)),
         trueCue = case_when(cueIdx < 3 ~ 80,
                             cueIdx == 3 ~ 50)) %>%
  group_by(subID) %>%
  mutate(logRT = log(RT),
         zlogRT = scale(logRT),
         cueIdx = factor(cueIdx),
         noise1frames_obs_z = scale(noise1frames_obs/60),
         signal1frames_obs_z = scale(signal1frames_obs/60),
         noise2frames_obs_z = scale(noise2frames_obs/60),
         signal2frames_obs_z = scale(signal2frames_obs/60),
         signal1Onset_z = scale(signal1Onset_design/60),
         signal2Onset_z = scale(signal2Onset_design/60),
         zlogRT_sig1locked = zlogRT - signal1Onset_z,
         zlogRT_sig2locked = zlogRT - signal2Onset_z) %>%
  ungroup()

# add estimated cue values
estimates <- learnVal_df %>%
  select(c(subID, block, cueName, cueIdx, estimate, congImgIdx, sliderValue)) %>%
  filter(subID != '33')

inference_df <- inference_df %>%
  mutate(subID = factor(subID),
         cueIdx = factor(cueIdx)) %>%
  left_join(., estimates, by=c('subID', 'block', 'cueName', 'cueIdx'))
```

```{r}



```


# LOAD & TIDY MODEL DATA FOR COMPARISONS
```{r}
model_df <- read.csv('steadyState_modelBehavior.csv')

# compute noise2frames_obs
signal2_model <- model_df %>% 
  filter(RT > noise2Onsets) %>%
  mutate(noise2frames_obs = case_when(RT < signal2Onsets ~ (noise2Onsets+noise2Frames) - RT,
                                      RT >= signal2Onsets ~ noise2Frames),
         congruent = case_when(cue==0.5 ~ 'neutral',
                               cue==0.8 & congruent==0 ~ 'incongruent',
                               cue==0.8 & congruent==1 ~ 'congruent'),
         congruent = factor(congruent, levels=c('incongruent', 'congruent', 'neutral')))
```

# NOISE2 EFFECTS: ACCURACY ~ NOISE2 * CUE
```{r noise 2 regressions}
signal2_behavior <- inference_df %>%
  filter(catch_trial == 0, respFrame >= noise2Onset_design)

plot_vals <- signal2_behavior %>% 
  select(noise2frames_obs, totalEv_signal1, totalEv_signal2) %>%
  summarise(noise_vals = quantile(noise2frames_obs, probs = seq(0,1,0.1), na.rm=T, names=F))

#### accuracy #### 
acc_emm <- glm(accuracy ~ noise2frames_obs * estimate, signal2_behavior, family='binomial') %>%
    emmeans(., ~ noise2frames_obs | estimate, type='response', 
            at=list(noise2frames_obs=plot_vals$noise_vals,
                    estimate = unique(signal2_behavior$estimate)))

acc_trends <- glm(accuracy ~ noise2frames_obs * estimate, signal2_behavior, family='binomial') %>% 
  emtrends(., 'estimate', var='noise2frames_obs', at=list(estimate=unique(signal2_behavior$estimate))) 

p1 <- acc_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise2frames_obs, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=estimate, group=estimate)) +
  theme_bw() +
  geom_pointrange() +
  geom_line() +
  scale_color_gradient(low = 'blue', high='green') +
  labs(y='p(correct)', title='correct response ~ noise2frames * subjectiveCue')

p2 <- acc_trends %>% as.data.frame() %>%
  ggplot(aes(x=estimate, y=noise2frames_obs.trend, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=estimate)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept = 0) +
  scale_color_gradient(low = 'blue', high='green') +
  labs(x='subjective cue probability', title='slope of noise2 effect') +
  theme(legend.position = 'none')

p1 + p2 & theme(axis.text = element_text(size=12))

ggsave('acc_noise2_obs*subjectiveCue.png', width=10, height=4)
```

# NOISE2 EFFECTS - CUECONGCHOICE
```{r}
# human behavior
cueCong_emm <- glm(cueCongResponse_obj ~ noise2frames_obs * congruent, signal2_behavior, family='binomial') %>%
    emmeans(., ~ noise2frames_obs | congruent, type='response', at=list(noise2frames_obs=plot_vals$noise_vals))

cueCong_trends <- glm(cueCongResponse_obj ~ noise2frames_obs * congruent, signal2_behavior, family='binomial') %>% 
  emtrends(., 'congruent', var='noise2frames_obs') 

p1 <- cueCong_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise2frames_obs, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent, fill=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept=0.5) +
  geom_line() +
  labs(y='p(chooseCue)', title='cueCongChoice ~ noise2frames * congruent')

p2 <- cueCong_trends %>% as.data.frame() %>%
  ggplot(aes(x=congruent, y=noise2frames_obs.trend, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept = 0) +
  labs(x='', title='slope of noise2 effect') +
  theme(legend.position = 'none')

p1 + p2 & theme(axis.text = element_text(size=12))

ggsave('chooseCue_noise2_obs*cong.png', width=10, height=4)

#### model predictions
signal2_model <- signal2_model %>%
  mutate(cueCongResponse = case_when(congruent=='congruent' & forcedChoice==1 ~ 1,
                                     congruent=='incongruent' & forcedChoice==0 ~ 1,
                                     congruent=='congruent' & forcedChoice==0 ~ 0,
                                     congruent=='incongruent' & forcedChoice==1 ~ 0))


cueCong_emm <- glm(cueCongResponse ~ noise2frames_obs * congruent, signal2_model, family='binomial') %>%
    emmeans(., ~ noise2frames_obs | congruent, type='response', 
            at=list(noise2frames_obs = quantile(signal2_model$noise2frames_obs, probs = seq(0,1,0.1), na.rm=T, names=F)))

cueCong_trends <- glm(cueCongResponse ~ noise2frames_obs * congruent, signal2_model, family='binomial') %>% 
  emtrends(., 'congruent', var='noise2frames_obs') 

p1 <- cueCong_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise2frames_obs, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent, fill=congruent)) +
  theme_bw() +
  geom_pointrange(shape=5) +
  geom_hline(yintercept=0.5) +
  geom_line() +
  labs(y='p(chooseCue)', title='cueCongChoice ~ noise2frames * congruent')

p2 <- cueCong_trends %>% as.data.frame() %>%
  ggplot(aes(x=congruent, y=noise2frames_obs.trend, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent)) +
  theme_bw() +
  geom_pointrange(shape=5) +
  geom_hline(yintercept = 0) +
  labs(x='', title='slope of noise2 effect') +
  theme(legend.position = 'none')

p1 + p2 & theme(axis.text = element_text(size=12))

ggsave('chooseCue_noise2_obs*cong_model.png', width=10, height=4)


## on the same timescale of noise2obs as humans
cueCong_emm <- glm(cueCongResponse ~ noise2frames_obs * congruent, signal2_model, family='binomial') %>%
    emmeans(., ~ noise2frames_obs | congruent, type='response', 
            at=list(noise2frames_obs = plot_vals$noise_vals))

cueCong_trends <- glm(cueCongResponse ~ noise2frames_obs * congruent, signal2_model, family='binomial') %>% 
  emtrends(., 'congruent', var='noise2frames_obs') 

p1 <- cueCong_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise2frames_obs, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent, fill=congruent)) +
  theme_bw() +
  geom_pointrange(shape=5) +
  geom_hline(yintercept=0.5) +
  geom_line() +
  labs(y='p(chooseCue)', title='cueCongChoice ~ noise2frames * congruent')

p2 <- cueCong_trends %>% as.data.frame() %>%
  ggplot(aes(x=congruent, y=noise2frames_obs.trend, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent)) +
  theme_bw() +
  geom_pointrange(shape=5) +
  geom_hline(yintercept = 0) +
  labs(x='', title='slope of noise2 effect') +
  theme(legend.position = 'none')

p1 + p2 & theme(axis.text = element_text(size=12))

ggsave('chooseCue_noise2_obs*cong_modelAbridged.png', width=10, height=4)
```

# NOISE 2 EFFECTS - RT
```{r}

rt_emm <- signal2_behavior %>%
  filter(respFrame > signal2Onset_design) %>%
  mutate(sig2locked_RT = respFrame - signal2Onset_design) %>%
  lm(sig2locked_RT ~ noise2frames_obs * congruent, .) %>%
  emmeans(., ~ noise2frames_obs | congruent, at=list(noise2frames_obs=plot_vals$noise_vals))

rt_trends <- signal2_behavior %>%
  filter(respFrame > signal2Onset_design) %>%
  mutate(sig2locked_RT = respFrame - signal2Onset_design) %>%
  lm(sig2locked_RT ~ noise2frames_obs * congruent, .) %>%
  emtrends(., 'congruent', var='noise2frames_obs')

p1 <- rt_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise2frames_obs, y=emmean, color=congruent, fill=congruent)) +
  theme_bw() + 
  geom_pointrange(aes(ymin=lower.CL, ymax=upper.CL)) +
  geom_line() +
  labs(y='respFrame - signal2Onset', title='sig2locked_respFrame ~ noise2frames * congruent')

p2 <- rt_trends %>% as.data.frame() %>%
  ggplot(aes(x=congruent, y=noise2frames_obs.trend, ymin=lower.CL, ymax=upper.CL, color=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept = 0) +
  labs(x='', title='slope of noise2 effect') +
  theme(legend.position = 'none')

p1 + p2 
ggsave('rt_noise2_obs*cong.png', width=10, height=4)

## adding decision accuracy as a predictor
rt_emm <- signal2_behavior %>%
  filter(respFrame > signal2Onset_design) %>%
  mutate(sig2locked_RT = respFrame - signal2Onset_design) %>%
  lm(sig2locked_RT ~ noise2frames_obs * congruent * accuracyFactor, .) %>%
  emmeans(., ~ noise2frames_obs | congruent*accuracyFactor, at=list(noise2frames_obs=plot_vals$noise_vals))

rt_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise2frames_obs, y=emmean, color=congruent, fill=congruent)) +
  theme_bw() + 
  geom_pointrange(aes(ymin=lower.CL, ymax=upper.CL)) +
  geom_line() +
  facet_wrap(~accuracyFactor) +
  labs(y='respFrame - signal2Onset', title='sig2locked_respFrame ~ noise2frames * congruent * accuracy')

ggsave('rt_noise2_obs*cong*accuracy.png', width=10, height=4)

###### model predictions
rt_emm <- signal2_model %>%
  filter(RT > signal2Onsets) %>%
  mutate(sig2locked_RT = RT - signal2Onsets) %>%
  lm(sig2locked_RT ~ noise2frames_obs * congruent, .) %>%
  emmeans(., ~ noise2frames_obs | congruent, at=list(noise2frames_obs=plot_vals$noise_vals))

rt_trends <- signal2_model %>%
  filter(RT > signal2Onsets) %>%
  mutate(sig2locked_RT = RT - signal2Onsets) %>%
  lm(sig2locked_RT ~ noise2frames_obs * congruent, .) %>%
  emtrends(., 'congruent', var='noise2frames_obs')

p1 <- rt_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise2frames_obs, y=emmean, color=congruent, fill=congruent)) +
  theme_bw() + 
  geom_pointrange(aes(ymin=lower.CL, ymax=upper.CL), shape=5) +
  geom_line() +
  labs(y='respFrame - signal2Onset', title='sig2locked_respFrame ~ noise2frames * congruent')

p2 <- rt_trends %>% as.data.frame() %>%
  ggplot(aes(x=congruent, y=noise2frames_obs.trend, ymin=lower.CL, ymax=upper.CL, color=congruent)) +
  theme_bw() +
  geom_pointrange(shape=5) +
  geom_hline(yintercept = 0) +
  labs(x='', title='slope of noise2 effect') +
  theme(legend.position = 'none')

p1 + p2 
ggsave('rt_noise2_obs*cong_model.png', width=10, height=4)


#### accuracy interaction
rt_emm <- signal2_model %>%
  filter(RT > signal2Onsets) %>%
  mutate(sig2locked_RT = RT - signal2Onsets) %>%
  lm(sig2locked_RT ~ noise2frames_obs * congruent * forcedChoice, .) %>%
  emmeans(., ~ noise2frames_obs | congruent*forcedChoice, at=list(noise2frames_obs=plot_vals$noise_vals))

rt_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise2frames_obs, y=emmean, color=congruent, fill=congruent)) +
  theme_bw() + 
  geom_pointrange(aes(ymin=lower.CL, ymax=upper.CL), shape=5) +
  geom_line() +
  facet_wrap(~forcedChoice) +
  labs(y='respFrame - signal2Onset', title='sig2locked_respFrame ~ noise2frames * congruent * accuracy')

ggsave('rt_noise2_obs*cong*accuracy_model.png', width=10, height=4)
```

# EFFECTS OF NOISE1 ON SIGNAL 1 CHOICE BIASES
```{r}

# cueCong response
cueCong_emm <- inference_test %>%
  filter(respFrame < noise2Onset_design) %>%
  glm(cueCongResponse_obj ~ noise1frames_obs * congruent, ., family='binomial') %>%
    emmeans(., ~ noise1frames_obs | congruent, type='response', at=list(noise1frames_obs=plot_vals$noise_vals))

cueCong_trends <- inference_test %>%
  filter(respFrame < noise2Onset_design) %>%
  glm(cueCongResponse_obj ~ noise1frames_obs * congruent, ., family='binomial') %>% 
  emtrends(., 'congruent', var='noise1frames_obs') 

p1 <- cueCong_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise1frames_obs, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent, fill=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept=0.5) +
  geom_line() +
  labs(y='p(chooseCue)', title='cueCongChoice ~ noise1frames * congruent')

p2 <- cueCong_trends %>% as.data.frame() %>%
  ggplot(aes(x=congruent, y=noise1frames_obs.trend, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept = 0) +
  labs(x='', title='slope of noise1 effect') +
  theme(legend.position = 'none')

p1 + p2 & theme(axis.text = element_text(size=12))

ggsave('chooseCue_noise1_obs*cong.png', width=10, height=4)
```


# NOISE RESPONDING DATA
```{r responses in noise 1 & noise 2}

# proportion of noise1 responses 
p1 <- inference_test %>%
  mutate(noise1resp = ifelse(respFrame < signal1Onset_design, 1, 0),
         noise1cue = ifelse(congruent=='neutral', '50%', '80%')) %>%
  group_by(noise1cue, subID) %>%
  summarise(noise1resp = mean(noise1resp)) %>%
  ggplot(aes(x=noise1cue, y=noise1resp)) +
  theme_bw() +
  geom_line(aes(group=subID), alpha=0.25, color='gray') +
  geom_point(aes(color=subID)) +
  scale_color_manual(values=c(unname(cols25()[1:13]), '#F8766D', '#619CFF')) +
  stat_summary(aes(color=noise1cue), fun.data = 'mean_se', position = position_dodge2(width=3)) +
  labs(y='', title='proportion of responses made during first noise') +
  theme(legend.position='none')

p2 <- inference_test %>%
  mutate(noise1resp = ifelse(respFrame < signal1Onset_design, 1, 0),
         noise1cue = ifelse(congruent=='neutral', '50%', '80%')) %>%
  ggplot(aes(x=sig1locked_rt/60, color=noise1cue, fill=noise1cue)) +
  theme_bw() +
  geom_histogram(alpha=0.5, bins=50) +
  geom_vline(xintercept=0) +
  labs(title = 'RT locked to onset of signal1', x='RT (seconds)')

# proportion of noise2 responses
p3 <- inference_test %>%
  mutate(noise2resp = ifelse(respFrame < signal2Onset_design & respFrame > noise2Onset_design, 1, 0)) %>%
  group_by(congruent, subID) %>%
  summarise(noise2resp = mean(noise2resp)) %>%
  ggplot(aes(x=congruent, y=noise2resp, color=subID)) +
  theme_bw() +
  geom_line(aes(group=subID), alpha=0.25, color='gray') +
  geom_point() +
  scale_color_manual(values=c(unname(cols25()[1:13]), "#F8766D", "#00BA38", "#619CFF")) +
  stat_summary(aes(color=congruent), fun.data = 'mean_se', position = position_dodge2(width=6)) +
  labs(y='', title='proportion of responses made during second noise', x='')

p4 <- inference_test %>%
  mutate(sig2locked_rt = (respFrame - signal2Onset_design)/60) %>%
  ggplot(aes(x=sig2locked_rt, color=congruent, fill=congruent)) +
  theme_bw() +
  geom_histogram(alpha=0.5, bins=50) +
  geom_vline(xintercept=0) +
  labs(title = 'RT locked to onset of signal2', x='RT (seconds)')
  
p1 + p2 + p3 + p4 + plot_layout(guides = 'collect')
ggsave('noiseResponseSummary.png', height=8, width=10)
```

# NOISE 1 EFFECTS
```{r}

plot_vals <- inference_test %>% 
  select(noise1frames_design) %>%
  summarise(noise_vals = quantile(noise1frames_design, probs = seq(0,1,0.1), na.rm=T, names=F))

#### accuracy #### 
acc_emm <- glm(accuracy ~ noise1frames_design * congruent, inference_test, family='binomial') %>%
    emmeans(., ~ noise1frames_design | congruent, type='response', at=list(noise1frames_design=plot_vals$noise_vals))

acc_trends <- glm(accuracy ~ noise1frames_design * congruent, inference_test, family='binomial') %>% 
  emtrends(., 'congruent', var='noise1frames_design') 

p1 <- acc_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise1frames_design, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent, fill=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_line() +
  labs(y='p(correct)', title='correct response ~ noise1frames * congruent')

p2 <- acc_trends %>% as.data.frame() %>%
  ggplot(aes(x=congruent, y=noise1frames_design.trend, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept = 0) +
  labs(x='', title='slope of noise1 effect') +
  theme(legend.position = 'none')

p1 + p2 & theme(axis.text = element_text(size=12))

ggsave('acc_noise1*cong.png', width=10, height=4)

rt_emm <- lm(sig1locked_rt ~ noise1frames_design * congruent, inference_test) %>%
  emmeans(., ~ noise1frames_design | congruent, at=list(noise1frames_design=plot_vals$noise_vals))

rt_trends <- lm(sig1locked_rt ~ noise1frames_design * congruent, inference_test) %>%
  emtrends(., 'congruent', var='noise1frames_design')

p1 <- rt_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise1frames_design, y=emmean, color=congruent, fill=congruent)) +
  theme_bw() + 
  geom_hline(yintercept = 0) +
  geom_pointrange(aes(ymin=lower.CL, ymax=upper.CL)) +
  geom_line() +
  labs(y='zlogRT', title='zlogRT ~ noise1frames * congruent')

p2 <- rt_trends %>% as.data.frame() %>%
  ggplot(aes(x=congruent, y=noise2frames_design.trend, ymin=lower.CL, ymax=upper.CL, color=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept = 0) +
  labs(x='', title='slope of noise2 effect') +
  theme(legend.position = 'none')

p1 + p2 & theme(axis.text = element_text(size=12))
ggsave('rt_noise2*cong.png', width=10, height=4)

# cueCong response
cueCong_emm <- glm(cueCongResponse_obj ~ noise2frames_design * congruent, signal2_behavior, family='binomial') %>%
    emmeans(., ~ noise2frames_design | congruent, type='response', at=list(noise2frames_design=plot_vals$noise_vals))

cueCong_trends <- glm(cueCongResponse_obj ~ noise2frames_design * congruent, signal2_behavior, family='binomial') %>% 
  emtrends(., 'congruent', var='noise2frames_design') 

p1 <- cueCong_emm %>% as.data.frame() %>%
  ggplot(aes(x=noise2frames_design, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent, fill=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept=0.5) +
  geom_line() +
  labs(y='p(chooseCue)', title='cueCongChoice ~ noise2frames * congruent')

p2 <- cueCong_trends %>% as.data.frame() %>%
  ggplot(aes(x=congruent, y=noise2frames_design.trend, ymin=asymp.LCL, ymax=asymp.UCL, 
             color=congruent)) +
  theme_bw() +
  geom_pointrange() +
  geom_hline(yintercept = 0) +
  labs(x='', title='slope of noise2 effect') +
  theme(legend.position = 'none')

p1 + p2 & theme(axis.text = element_text(size=12))

ggsave('chooseCue_noise2*cong.png', width=10, height=4)
```
```